// Gameplay values
export const Action = {

	NULL_ACTION: "NULL_ACTION",

	NORTH: "NORTH",
	SOUTH: "SOUTH",
	EAST: "EAST",
	WEST: "WEST",
	NORTHEAST: "NORTHEAST",
	NORTHWEST: "NORTHWEST",
	SOUTHEAST: "SOUTHEAST",
	SOUTHWEST: "SOUTHWEST",
	UP: "UP",
	DOWN: "DOWN",
	IN: "IN",
	OUT: "OUT",
	WALK: "WALK",
	GO: "GO",
	SLIDE: "SLIDE",
	SWIM: "SWIM",
	EXIT: "EXIT",
	CROSS: "CROSS",
	LAUNCH: "LAUNCH",
	LAND: "LAND",

	BRIEF: "BRIEF",
	DEFEND: "DEFEND",
	DELETE: "DELETE",
	DIAGNOSE: "DIAGNOSE",
	INVENTORY: "INVENTORY",
	JUMP: "JUMP",
	LOOK: "LOOK",
	PRAY: "PRAY",
	QUIT: "QUIT",
	RESTART: "RESTART",
	RESTORE: "RESTORE",
	SAVE: "SAVE",
	SAY: "SAY",
	SCORE: "SCORE",
	SHOUT: "SHOUT",
	STAY: "STAY",
	SUPERBRIEF: "SUPERBRIEF",
	UNDO: "UNDO",
	VERBOSE: "VERBOSE",
	WAIT: "WAIT",

	ACTIVATE: "ACTIVATE",
	ANSWER: "ANSWER",
	BLOW: "BLOW",
	BOARD: "BOARD",
	BRUSH: "BRUSH",
	CLIMB: "CLIMB",
	CLOSE: "CLOSE",
	COUNT: "COUNT",
	DEBOARD: "DEBOARD",
	DEFLATE: "DEFLATE",
	DRINK: "DRINK",
	DROP: "DROP",
	EAT: "EAT",
	ENTER: "ENTER",
	EXAMINE: "EXAMINE",
	EXTINGUISH: "EXTINGUISH",
	FOLLOW: "FOLLOW",
	GREET: "GREET",
	KICK: "KICK",
	KNOCK: "KNOCK",
	LIGHT: "LIGHT",
	LISTEN: "LISTEN",
	LOOK_IN: "LOOK_IN",
	LOOK_OUT: "LOOK_OUT",
	LOOK_UNDER: "LOOK_UNDER",
	LOWER: "LOWER",
	MOVE_OBJECT: "MOVE_OBJECT",
	OPEN: "OPEN",
	PLAY: "PLAY",
	POUR: "POUR",
	PULL: "PULL",
	PUSH: "PUSH",
	RAISE: "RAISE",
	READ: "READ",
	REMOVE: "REMOVE",
	REPAIR: "REPAIR",
	RING: "RING",
	SEARCH: "SEARCH",
	SHAKE: "SHAKE",
	SMELL: "SMELL",
	STRIKE: "STRIKE",
	TAKE: "TAKE",
	TALK_TO: "TALK_TO",
	TOUCH: "TOUCH",
	UNTIE: "UNTIE",
	WAKE: "WAKE",
	WAVE: "WAVE",
	WEAR: "WEAR",
	WIND: "WIND",

	ATTACK: "ATTACK",
	BREAK: "BREAK",
	BURN: "BURN",
	CUT: "CUT",
	DIG: "DIG",
	FILL: "FILL",
	INFLATE: "INFLATE",
	LOCK: "LOCK",
	TURN: "TURN",
	UNLOCK: "UNLOCK",

	GIVE: "GIVE",
	PUT: "PUT",
	TIE: "TIE",
	THROW: "THROW",

	AGAIN: "AGAIN"

};

export const ActionType = {
	NULL_TYPE: "NULL_TYPE",
	DIRECT: "DIRECT",
	EXIT: "EXIT",
	INDIRECT: "INDIRECT",
	INDIRECT_INVERSE: "INDIRECT_INVERSE",
	MULTIPLE: "MULTIPLE",
	REFLEXIVE: "REFLEXIVE",
	SPEAK: "SPEAK",
	SWITCH: "SWITCH"
};

export const CONSTANTS = {
	CARRY_WEIGHT_LIMIT: 100,
	DEATH_POINTS: 10,
	LANTERN_LIFESPAN: 500,
	MAX_PLAYER_DEATHS: 3,
	MAX_DARKNESS_TURNS: 2,
	MAX_HIT_POINTS: 10,
	MATCH_LIFESPAN: 2,
	MATCHES_IN_BOOK: 20,
	RESERVOIR_DRAIN_TURNS: 8,
	SHAFT_BASKET_POINTS: 13,
	SPIRIT_CEREMONY_LENGTH: 5,
	THIEF_OPENS_EGG: 5,
	WINNING_SCORE: 350,

	MAX_INPUT_LENGTH: 50,
	MAX_TURNS: 2000,

	// from Actor object
	CYCLOPS_CYCLE_MAX: 8,
	MAX_ENEMY_HIT_POINTS: 10,
	THIEF_ENCOUNTER_PERCENT: 2,
	SONGBIRD_CHIRP_PERCENT: 15,

	// Score values for acquiring a treasure and putting it in the case
	PLATINUM_VALUE: 10,
	PLATINUM_TROPHY_VALUE: 5,
	BAUBLE_VALUE: 1,
	BAUBLE_TROPHY_VALUE: 1,
	CHALICE_VALUE: 10,
	CHALICE_TROPHY_VALUE: 5,
	COFFIN_VALUE: 10,
	COFFIN_TROPHY_VALUE: 15,
	COINS_VALUE: 10,
	COINS_TROPHY_VALUE: 5,
	CANARY_VALUE: 6,
	CANARY_TROPHY_VALUE: 4,
	DIAMOND_VALUE: 10,
	DIAMOND_TROPHY_VALUE: 10,
	EGG_VALUE: 5,
	EGG_TROPHY_VALUE: 5,
	EMERALD_VALUE: 5,
	EMERALD_TROPHY_VALUE: 10,
	JADE_VALUE: 5,
	JADE_TROPHY_VALUE: 5,
	PAINTING_VALUE: 4,
	PAINTING_TROPHY_VALUE: 6,
	POT_OF_GOLD_VALUE: 10,
	POT_OF_GOLD_TROPHY_VALUE: 10,
	SAPPHIRE_VALUE: 5,
	SAPPHIRE_TROPHY_VALUE: 5,
	SCARAB_VALUE: 5,
	SCARAB_TROPHY_VALUE: 5,
	SCEPTRE_VALUE: 4,
	SCEPTRE_TROPHY_VALUE: 6,
	CRYSTAL_SKULL_VALUE: 10,
	CRYSTAL_SKULL_TROPHY_VALUE: 10,
	TORCH_VALUE: 14,
	TORCH_TROPHY_VALUE: 6,
	TRIDENT_VALUE: 4,
	TRIDENT_TROPHY_VALUE: 11,
	TRUNK_OF_JEWELS_VALUE: 15,
	TRUNK_OF_JEWELS_TROPHY_VALUE: 5,

	BROKEN_EGG_TROPHY_VALUE: 2,
	BROKEN_CANARY_TROPHY_VALUE: 1,

	// Score values for reaching specific rooms
	KITCHEN_VALUE: 10,
	CELLAR_VALUE: 25,
	EAST_WEST_VALUE: 5,
	TREASURE_VALUE: 25,

	// Item weights
	BAR_WEIGHT: 20,
	BAUBLE_WEIGHT: 0,
	CHALICE_WEIGHT: 10,
	COFFIN_WEIGHT: 55,
	COINS_WEIGHT: 15,
	CANARY_WEIGHT: 4,
	DIAMOND_WEIGHT: 6,
	EGG_WEIGHT: 5,
	EMERALD_WEIGHT: 6,
	JADE_WEIGHT: 10,
	PAINTING_WEIGHT: 15,
	POT_OF_GOLD_WEIGHT: 15,
	SAPPHIRE_WEIGHT: 10,
	SCARAB_WEIGHT: 8,
	SCEPTRE_WEIGHT: 3,
	SKULL_WEIGHT: 15,
	TORCH_WEIGHT: 20,
	TRIDENT_WEIGHT: 20,
	TRUNK_WEIGHT: 35,

	ANCIENT_MAP_WEIGHT: 2,
	AXE_WEIGHT: 25,
	BELL_WEIGHT: 10,
	BLACK_BOOK_WEIGHT: 10,
	BOAT_LABEL_WEIGHT: 2,
	BOTTLE_WEIGHT: 5,
	BROKEN_CANARY_WEIGHT: 4,
	BROKEN_EGG_WEIGHT: 5,
	BUOY_WEIGHT: 10,
	CANDLES_WEIGHT: 10,
	COAL_WEIGHT: 20,
	BOAT_WEIGHT: 20,
	GARLIC_WEIGHT: 4,
	GUIDEBOOK_WEIGHT: 2,
	GUNK_WEIGHT: 6,
	KNIFE_WEIGHT: 10,
	LANTERN_WEIGHT: 15,
	LEAVES_WEIGHT: 25,
	LEAFLET_WEIGHT: 2,
	LUNCH_WEIGHT: 5,
	MATCHBOOK_WEIGHT: 2,
	NEST_WEIGHT: 5,
	PUMP_WEIGHT: 8,
	ROPE_WEIGHT: 10,
	RUSTY_KNIFE_WEIGHT: 20,
	SACK_WEIGHT: 9,
	SCREWDRIVER_WEIGHT: 2,
	SHOVEL_WEIGHT: 15,
	SKELETON_KEY_WEIGHT: 10,
	STILETTO_WEIGHT: 10,
	SWORD_WEIGHT: 30,
	TIMBER_WEIGHT: 50,
	TUBE_WEIGHT: 5,
	USELESS_LANTERN_WEIGHT: 20,
	VITREOUS_SLAG_WEIGHT: 10,
	WRENCH_WEIGHT: 10,
	ZORK_MANUAL_WEIGHT: 2,

	actions: {
		"north": {action: Action.NORTH, type: ActionType.EXIT},
		"go north": {action: Action.NORTH, type: ActionType.EXIT},
		"walk north": {action: Action.NORTH, type: ActionType.EXIT},
		"exit north": {action: Action.NORTH, type: ActionType.EXIT},
		"n": {action: Action.NORTH, type: ActionType.EXIT},
		"go n": {action: Action.NORTH, type: ActionType.EXIT},
		"walk n": {action: Action.NORTH, type: ActionType.EXIT},
		"exit n": {action: Action.NORTH, type: ActionType.EXIT},

		"south": {action: Action.SOUTH, type: ActionType.EXIT},
		"go south": {action: Action.SOUTH, type: ActionType.EXIT},
		"walk south": {action: Action.SOUTH, type: ActionType.EXIT},
		"exit south": {action: Action.SOUTH, type: ActionType.EXIT},
		"s": {action: Action.SOUTH, type: ActionType.EXIT},
		"go s": {action: Action.SOUTH, type: ActionType.EXIT},
		"walk s": {action: Action.SOUTH, type: ActionType.EXIT},
		"exit s": {action: Action.SOUTH, type: ActionType.EXIT},

		"east": {action: Action.EAST, type: ActionType.EXIT},
		"go east": {action: Action.EAST, type: ActionType.EXIT},
		"walk east": {action: Action.EAST, type: ActionType.EXIT},
		"exit east": {action: Action.EAST, type: ActionType.EXIT},
		"e": {action: Action.EAST, type: ActionType.EXIT},
		"go e": {action: Action.EAST, type: ActionType.EXIT},
		"walk e": {action: Action.EAST, type: ActionType.EXIT},
		"exit e": {action: Action.EAST, type: ActionType.EXIT},

		"west": {action: Action.WEST, type: ActionType.EXIT},
		"go west": {action: Action.WEST, type: ActionType.EXIT},
		"walk west": {action: Action.WEST, type: ActionType.EXIT},
		"exit west": {action: Action.WEST, type: ActionType.EXIT},
		"w": {action: Action.WEST, type: ActionType.EXIT},
		"go w": {action: Action.WEST, type: ActionType.EXIT},
		"walk w": {action: Action.WEST, type: ActionType.EXIT},
		"exit w": {action: Action.WEST, type: ActionType.EXIT},

		"northeast": {action: Action.NORTHEAST, type: ActionType.EXIT},
		"go northeast": {action: Action.NORTHEAST, type: ActionType.EXIT},
		"walk northeast": {action: Action.NORTHEAST, type: ActionType.EXIT},
		"exit northeast": {action: Action.NORTHEAST, type: ActionType.EXIT},
		"ne": {action: Action.NORTHEAST, type: ActionType.EXIT},
		"go ne": {action: Action.NORTHEAST, type: ActionType.EXIT},
		"walk ne": {action: Action.NORTHEAST, type: ActionType.EXIT},
		"exit ne": {action: Action.NORTHEAST, type: ActionType.EXIT},

		"northwest": {action: Action.NORTHWEST, type: ActionType.EXIT},
		"go northwest": {action: Action.NORTHWEST, type: ActionType.EXIT},
		"walk northwest": {action: Action.NORTHWEST, type: ActionType.EXIT},
		"exit northwest": {action: Action.NORTHWEST, type: ActionType.EXIT},
		"nw": {action: Action.NORTHWEST, type: ActionType.EXIT},
		"go nw": {action: Action.NORTHWEST, type: ActionType.EXIT},
		"walk nw": {action: Action.NORTHWEST, type: ActionType.EXIT},
		"exit nw": {action: Action.NORTHWEST, type: ActionType.EXIT},

		"southeast": {action: Action.SOUTHEAST, type: ActionType.EXIT},
		"go southeast": {action: Action.SOUTHEAST, type: ActionType.EXIT},
		"walk southeast": {action: Action.SOUTHEAST, type: ActionType.EXIT},
		"exit southeast": {action: Action.SOUTHEAST, type: ActionType.EXIT},
		"se": {action: Action.SOUTHEAST, type: ActionType.EXIT},
		"go se": {action: Action.SOUTHEAST, type: ActionType.EXIT},
		"walk se": {action: Action.SOUTHEAST, type: ActionType.EXIT},
		"exit se": {action: Action.SOUTHEAST, type: ActionType.EXIT},

		"southwest": {action: Action.SOUTHWEST, type: ActionType.EXIT},
		"go southwest": {action: Action.SOUTHWEST, type: ActionType.EXIT},
		"walk southwest": {action: Action.SOUTHWEST, type: ActionType.EXIT},
		"exit southwest": {action: Action.SOUTHWEST, type: ActionType.EXIT},
		"sw": {action: Action.SOUTHWEST, type: ActionType.EXIT},
		"go sw": {action: Action.SOUTHWEST, type: ActionType.EXIT},
		"walk sw": {action: Action.SOUTHWEST, type: ActionType.EXIT},
		"exit sw": {action: Action.SOUTHWEST, type: ActionType.EXIT},

		// 	"climb up": {action: Action.UP, type: ActionType.EXIT},
		"up": {action: Action.UP, type: ActionType.EXIT},
		"go up": {action: Action.UP, type: ActionType.EXIT},
		"u": {action: Action.UP, type: ActionType.EXIT},
		"go u": {action: Action.UP, type: ActionType.EXIT},

		"climb down": {action: Action.DOWN, type: ActionType.EXIT},
		"down": {action: Action.DOWN, type: ActionType.EXIT},
		"go down": {action: Action.DOWN, type: ActionType.EXIT},
		"d": {action: Action.DOWN, type: ActionType.EXIT},
		"go d": {action: Action.DOWN, type: ActionType.EXIT},

		"land": {action: Action.LAND, type: ActionType.EXIT},
		"in": {action: Action.IN, type: ActionType.EXIT},
		"inside": {action: Action.IN, type: ActionType.EXIT},
		"go in": {action: Action.IN, type: ActionType.EXIT},
		"go inside": {action: Action.IN, type: ActionType.EXIT},
		"out": {action: Action.OUT, type: ActionType.EXIT},
		"go out": {action: Action.OUT, type: ActionType.EXIT},
		"go outside": {action: Action.OUT, type: ActionType.EXIT},
		"outside": {action: Action.OUT, type: ActionType.EXIT},
		"exit": {action: Action.OUT, type: ActionType.EXIT},
		"slide": {action: Action.SLIDE, type: ActionType.EXIT},
		"swim": {action: Action.SWIM, type: ActionType.EXIT},

		// Reflexive actions: no interaction with game objects
		"brief": {action: Action.BRIEF, type: ActionType.REFLEXIVE},
		"deboard": {action: Action.DEBOARD, type: ActionType.REFLEXIVE},
		"delete": {action: Action.DELETE, type: ActionType.REFLEXIVE},
		"disembark": {action: Action.DEBOARD, type: ActionType.REFLEXIVE},
		"exit boat": {action: Action.DEBOARD, type: ActionType.REFLEXIVE},
		"get out": {action: Action.DEBOARD, type: ActionType.REFLEXIVE},
		"get out of boat": {action: Action.DEBOARD, type: ActionType.REFLEXIVE},
		"leave boat": {action: Action.DEBOARD, type: ActionType.REFLEXIVE},
		"diagnose": {action: Action.DIAGNOSE, type: ActionType.REFLEXIVE},
		"inventory": {action: Action.INVENTORY, type: ActionType.REFLEXIVE},
		"i": {action: Action.INVENTORY, type: ActionType.REFLEXIVE},
		"jump": {action: Action.JUMP, type: ActionType.REFLEXIVE},
		"leap": {action: Action.JUMP, type: ActionType.REFLEXIVE},
		"look around": {action: Action.LOOK, type: ActionType.REFLEXIVE},
		"look": {action: Action.LOOK, type: ActionType.REFLEXIVE},
		"l": {action: Action.LOOK, type: ActionType.REFLEXIVE},
		"quit": {action: Action.QUIT, type: ActionType.REFLEXIVE},
		"q": {action: Action.QUIT, type: ActionType.REFLEXIVE},
		"restart": {action: Action.RESTART, type: ActionType.REFLEXIVE},
		"restart game": {action: Action.RESTART, type: ActionType.REFLEXIVE},
		"restore": {action: Action.RESTORE, type: ActionType.REFLEXIVE},
		"restore file": {action: Action.RESTORE, type: ActionType.REFLEXIVE},
		"restore game": {action: Action.RESTORE, type: ActionType.REFLEXIVE},
		"load": {action: Action.RESTORE, type: ActionType.REFLEXIVE},
		"load game": {action: Action.RESTORE, type: ActionType.REFLEXIVE},
		"load file": {action: Action.RESTORE, type: ActionType.REFLEXIVE},
		"save": {action: Action.SAVE, type: ActionType.REFLEXIVE},
		"save game": {action: Action.SAVE, type: ActionType.REFLEXIVE},
		"score": {action: Action.SCORE, type: ActionType.REFLEXIVE},
		"shout": {action: Action.SHOUT, type: ActionType.REFLEXIVE},
		"yell": {action: Action.SHOUT, type: ActionType.REFLEXIVE},
		"scream": {action: Action.SHOUT, type: ActionType.REFLEXIVE},
		"superbrief": {action: Action.SUPERBRIEF, type: ActionType.REFLEXIVE},
		"pray": {action: Action.PRAY, type: ActionType.REFLEXIVE},
		"undo": {action: Action.UNDO, type: ActionType.REFLEXIVE},
		"verbose": {action: Action.VERBOSE, type: ActionType.REFLEXIVE},
		"wait": {action: Action.WAIT, type: ActionType.REFLEXIVE},

		// Direct object interaction actions
		"answer": {action: Action.ANSWER, type: ActionType.DIRECT},
		"blow": {action: Action.BLOW, type: ActionType.DIRECT},
		"blow out": {action: Action.BLOW, type: ActionType.DIRECT},
		"board": {action: Action.BOARD, type: ActionType.DIRECT},
		"get on": {action: Action.BOARD, type: ActionType.DIRECT},
		"get in": {action: Action.BOARD, type: ActionType.DIRECT},
		"sit on": {action: Action.BOARD, type: ActionType.DIRECT},
		"brush": {action: Action.BRUSH, type: ActionType.DIRECT},
		"climb": {action: Action.CLIMB, type: ActionType.DIRECT},
		"climb up": {action: Action.CLIMB, type: ActionType.DIRECT},
		"close": {action: Action.CLOSE, type: ActionType.DIRECT},
		"shut": {action: Action.CLOSE, type: ActionType.DIRECT},
		"count": {action: Action.COUNT, type: ActionType.DIRECT},
		"cross": {action: Action.CROSS, type: ActionType.DIRECT},
		"deflate": {action: Action.DEFLATE, type: ActionType.DIRECT},
		"uninflate": {action: Action.DEFLATE, type: ActionType.DIRECT},
		"drink": {action: Action.DRINK, type: ActionType.DIRECT},
		"drop": {action: Action.DROP, type: ActionType.DIRECT},
		"eat": {action: Action.EAT, type: ActionType.DIRECT},
		"enter": {action: Action.ENTER, type: ActionType.DIRECT},
		"examine": {action: Action.EXAMINE, type: ActionType.DIRECT},
		"launch": {action: Action.LAUNCH, type: ActionType.DIRECT},
		"look at": {action: Action.EXAMINE, type: ActionType.DIRECT},
		"l at": {action: Action.EXAMINE, type: ActionType.DIRECT},
		"extinguish": {action: Action. EXTINGUISH, type: ActionType.DIRECT},
		"turn off": {action: Action. EXTINGUISH, type: ActionType.DIRECT},
		"follow": {action: Action.FOLLOW, type: ActionType.DIRECT},
		"greet": {action: Action.GREET, type: ActionType.DIRECT},
		"hello": {action: Action.GREET, type: ActionType.DIRECT},
		"say hello": {action: Action.GREET, type: ActionType.DIRECT},
		"kick": {action: Action.KICK, type: ActionType.DIRECT},
		"knock": {action: Action.KNOCK, type: ActionType.DIRECT},
		"light": {action: Action.LIGHT, type: ActionType.SWITCH},
		"turn on": {action: Action.LIGHT, type: ActionType.DIRECT},
		"listen": {action: Action.LISTEN, type: ActionType.DIRECT},
		"look in": {action: Action.LOOK_IN, type: ActionType.DIRECT},
		"l in": {action: Action.LOOK_IN, type: ActionType.DIRECT},
		"look out": {action: Action.LOOK_OUT, type: ActionType.DIRECT},
		"l out": {action: Action.LOOK_OUT, type: ActionType.DIRECT},
		"look under": {action: Action.LOOK_UNDER, type: ActionType.DIRECT},
		"l under": {action: Action.LOOK_UNDER, type: ActionType.DIRECT},
		"lower": {action: Action.LOWER, type: ActionType.DIRECT},
		"move": {action: Action.MOVE_OBJECT, type: ActionType.DIRECT},
		"open": {action: Action.OPEN, type: ActionType.DIRECT},
		"pull": {action: Action.PULL, type: ActionType.DIRECT},
		"press": {action: Action.PUSH, type: ActionType.DIRECT},
		"push": {action: Action.PUSH, type: ActionType.DIRECT},
		"raise": {action: Action.RAISE, type: ActionType.DIRECT},
		"read": {action: Action.READ, type: ActionType.DIRECT},
		"remove": {action: Action.REMOVE, type: ActionType.DIRECT},
		"mend": {action: Action.REPAIR, type: ActionType.DIRECT},
		"repair": {action: Action.REPAIR, type: ActionType.DIRECT},
		"fix": {action: Action.REPAIR, type: ActionType.DIRECT},
		"ring": {action: Action.RING, type: ActionType.DIRECT},
		"search": {action: Action.SEARCH, type: ActionType.DIRECT},
		"shake": {action: Action.SHAKE, type: ActionType.DIRECT},
		"smell": {action: Action.SMELL, type: ActionType.DIRECT},
		"stay": {action: Action.STAY, type: ActionType.DIRECT},
		"take": {action: Action.TAKE, type: ActionType.DIRECT},
		"pick up": {action: Action.TAKE, type: ActionType.DIRECT},
		"get": {action: Action.TAKE, type: ActionType.DIRECT},
		"acquire": {action: Action.TAKE, type: ActionType.DIRECT},
		"talk to": {action: Action.TALK_TO, type: ActionType.DIRECT},
		"touch": {action: Action.TOUCH, type: ActionType.DIRECT},
		"detach": {action: Action.UNTIE, type: ActionType.DIRECT},
		"untie": {action: Action.UNTIE, type: ActionType.DIRECT},
		"wake": {action: Action.WAKE, type: ActionType.DIRECT},
		"wave": {action: Action.WAVE, type: ActionType.DIRECT},
		"wear": {action: Action.WEAR, type: ActionType.DIRECT},
		"wind": {action: Action.WIND, type: ActionType.DIRECT},
		"say": {action: Action.SAY, type: ActionType.SPEAK},

		// Indirect actions
		"attack": {action: Action.ATTACK, type: ActionType.SWITCH},
		"kill": {action: Action.ATTACK, type: ActionType.INDIRECT},
		"hit": {action: Action.ATTACK, type: ActionType.INDIRECT},
		"fight": {action: Action.ATTACK, type: ActionType.INDIRECT},
		"break": {action: Action.BREAK, type: ActionType.INDIRECT},
		"destroy": {action: Action.BREAK, type: ActionType.INDIRECT},
		"burn": {action: Action.BURN, type: ActionType.INDIRECT},
		"cut": {action: Action.CUT, type: ActionType.INDIRECT},
		"dig": {action: Action.DIG, type: ActionType.INDIRECT},
		"dig in": {action: Action.DIG, type: ActionType.INDIRECT},
		"fill": {action: Action.FILL, type: ActionType.INDIRECT},
		"inflate": {action: Action.INFLATE, type: ActionType.INDIRECT},
		"pour": {action: Action.POUR, type: ActionType.INDIRECT},
		"pump up": {action: Action.INFLATE, type: ActionType.INDIRECT},
		"pump": {action: Action.INFLATE, type: ActionType.INDIRECT},

		"turn": {action: Action.TURN, type: ActionType.INDIRECT},
		"unlock": {action: Action.UNLOCK, type: ActionType.INDIRECT},
		"lock": {action: Action.LOCK, type: ActionType.INDIRECT},
		"strike": {action: Action.STRIKE, type: ActionType.INDIRECT},
		"throw": {action: Action.THROW, type: ActionType.INDIRECT},

		"give": {action: Action.GIVE, type: ActionType.INDIRECT_INVERSE},
		"place": {action: Action.PUT, type: ActionType.INDIRECT_INVERSE},
		"put": {action: Action.PUT, type: ActionType.INDIRECT_INVERSE},
		"tie": {action: Action.TIE, type: ActionType.INDIRECT_INVERSE},
	},

	prepositions: {
		"ATTACK": "with",
		"BREAK": "with",
		"BURN": "with",
		"CUT": "with",
		"DIG": "with",
		"FILL": "with",
		"GIVE": "to",
		"INFLATE": "with",
		"LOCK": "with",
		"PUT": "in",
		"THROW": "at",
		"TIE": "to",
		"TURN": "with",
		"UNLOCK": "with"
	},

	Location: {

		NULL_LOCATION: "NULL_LOCATION",
		NULL_INVENTORY: "NULL_INVENTORY",
		WEST_OF_HOUSE: "WEST_OF_HOUSE",
		NORTH_OF_HOUSE: "NORTH_OF_HOUSE",
		BEHIND_HOUSE: "BEHIND_HOUSE",
		SOUTH_OF_HOUSE: "SOUTH_OF_HOUSE",
		ATTIC: "ATTIC",
		KITCHEN: "KITCHEN",
		LIVING_ROOM: "LIVING_ROOM",
		FOREST_PATH: "FOREST_PATH",
		FOREST_WEST: "FOREST_WEST",
		FOREST_EAST: "FOREST_EAST",
		FOREST_NORTHEAST: "FOREST_NORTHEAST",
		FOREST_SOUTH: "FOREST_SOUTH",
		CLEARING_NORTH: "CLEARING_NORTH",
		CLEARING_EAST: "CLEARING_EAST",
		UP_TREE: "UP_TREE",
		CANYON_VIEW: "CANYON_VIEW",
		ROCKY_LEDGE: "ROCKY_LEDGE",
		CANYON_BOTTOM: "CANYON_BOTTOM",
		END_OF_RAINBOW: "END_OF_RAINBOW",
		STONE_BARROW: "STONE_BARROW",
		INSIDE_STONE_BARROW: "INSIDE_STONE_BARROW",

		CELLAR: "CELLAR",
		EAST_OF_CHASM: "EAST_OF_CHASM",
		GALLERY: "GALLERY",
		STUDIO: "STUDIO",
		TROLL_ROOM: "TROLL_ROOM",
		EAST_WEST_PASSAGE: "EAST_WEST_PASSAGE",
		ROUND_ROOM: "ROUND_ROOM",
		NARROW_PASSAGE: "NARROW_PASSAGE",
		MIRROR_ROOM_SOUTH: "MIRROR_ROOM_SOUTH",
		WINDING_PASSAGE: "WINDING_PASSAGE",
		CAVE_SOUTH: "CAVE_SOUTH",
		ENTRANCE_TO_HADES: "ENTRANCE_TO_HADES",
		LAND_OF_THE_DEAD: "LAND_OF_THE_DEAD",
		ALTAR: "ALTAR",
		TEMPLE: "TEMPLE",
		EGYPTIAN_ROOM: "EGYPTIAN_ROOM",
		TORCH_ROOM: "TORCH_ROOM",
		DOME_ROOM: "DOME_ROOM",
		ENGRAVINGS_CAVE: "ENGRAVINGS_CAVE",

		LOUD_ROOM: "LOUD_ROOM",
		DAMP_CAVE: "DAMP_CAVE",
		WHITE_CLIFFS_BEACH_NORTH: "WHITE_CLIFFS_BEACH_NORTH",
		WHITE_CLIFFS_BEACH_SOUTH: "WHITE_CLIFFS_BEACH_SOUTH",
		FRIGID_RIVER_1: "FRIGID_RIVER_1",
		FRIGID_RIVER_2: "FRIGID_RIVER_2",
		FRIGID_RIVER_3: "FRIGID_RIVER_3",
		FRIGID_RIVER_4: "FRIGID_RIVER_4",
		FRIGID_RIVER_5: "FRIGID_RIVER_5",
		SANDY_BEACH: "SANDY_BEACH",
		SANDY_CAVE: "SANDY_CAVE",
		SHORE: "SHORE",
		ARAGAIN_FALLS: "ARAGAIN_FALLS",
		ON_THE_RAINBOW: "ON_THE_RAINBOW",
		DAM_BASE: "DAM_BASE",
		DAM: "DAM",
		DAM_LOBBY: "DAM_LOBBY",
		MAINTENANCE_ROOM: "MAINTENANCE_ROOM",

		NORTH_SOUTH_PASSAGE: "NORTH_SOUTH_PASSAGE",
		CHASM: "CHASM",
		DEEP_CANYON: "DEEP_CANYON",
		RESERVOIR_SOUTH: "RESERVOIR_SOUTH",
		STREAM_VIEW: "STREAM_VIEW",
		STREAM: "STREAM",
		RESERVOIR: "RESERVOIR",
		RESERVOIR_EMPTY: "RESERVOIR_EMPTY",
		RESERVOIR_NORTH: "RESERVOIR_NORTH",
		ATLANTIS_ROOM: "ATLANTIS_ROOM",
		CAVE_NORTH: "CAVE_NORTH",
		TWISTING_PASSAGE: "TWISTING_PASSAGE",
		MIRROR_ROOM_NORTH: "MIRROR_ROOM_NORTH",
		COLD_PASSAGE: "COLD_PASSAGE",
		SLIDE_ROOM: "SLIDE_ROOM",
		MINE_ENTRANCE: "MINE_ENTRANCE",
		SQUEAKY_ROOM: "SQUEAKY_ROOM",
		BAT_ROOM: "BAT_ROOM",

		SHAFT_ROOM: "SHAFT_ROOM",
		SMELLY_ROOM: "SMELLY_ROOM",
		GAS_ROOM: "GAS_ROOM",
		COAL_MINE_1: "COAL_MINE_1",
		COAL_MINE_2: "COAL_MINE_2",
		COAL_MINE_3: "COAL_MINE_3",
		COAL_MINE_4: "COAL_MINE_4",
		LADDER_TOP: "LADDER_TOP",
		LADDER_BOTTOM: "LADDER_BOTTOM",
		DEAD_END_COAL_MINE: "DEAD_END_COAL_MINE",
		TIMBER_ROOM: "TIMBER_ROOM",
		DRAFTY_ROOM: "DRAFTY_ROOM",
		MACHINE_ROOM: "MACHINE_ROOM",

		GRATING_ROOM: "GRATING_ROOM",
		CYCLOPS_ROOM: "CYCLOPS_ROOM",
		STRANGE_PASSAGE: "STRANGE_PASSAGE",
		TREASURE_ROOM: "TREASURE_ROOM",
		TREASURE_ROOM_INVISIBLE: "TREASURE_ROOM_INVISIBLE",

		MAZE_1: "MAZE_1",
		MAZE_2: "MAZE_2",
		MAZE_3: "MAZE_3",
		MAZE_4: "MAZE_4",
		MAZE_5: "MAZE_5",
		MAZE_6: "MAZE_6",
		MAZE_7: "MAZE_7",
		MAZE_8: "MAZE_8",
		MAZE_9: "MAZE_9",
		MAZE_10: "MAZE_10",
		MAZE_11: "MAZE_11",
		MAZE_12: "MAZE_12",
		MAZE_13: "MAZE_13",
		MAZE_14: "MAZE_14",
		MAZE_15: "MAZE_15",
		DEAD_END_MAZE_NORTH: "DEAD_END_MAZE_NORTH",
		DEAD_END_MAZE_SOUTHEAST: "DEAD_END_MAZE_SOUTHEAST",
		DEAD_END_MAZE_CENTER: "DEAD_END_MAZE_CENTER",
		DEAD_END_MAZE_SOUTHWEST: "DEAD_END_MAZE_SOUTHWEST",

		INSIDE_BIRDS_NEST: "INSIDE_BIRDS_NEST",
		INSIDE_BROKEN_EGG: "INSIDE_BROKEN_EGG",
		INSIDE_BUOY: "INSIDE_BUOY",
		INSIDE_COFFIN: "INSIDE_COFFIN",
		INSIDE_EGG: "INSIDE_EGG",
		INSIDE_MAILBOX: "INSIDE_MAILBOX",
		INSIDE_TROPHY_CASE: "INSIDE_TROPHY_CASE",
		INSIDE_SACK: "INSIDE_SACK",
		INSIDE_BOAT: "INSIDE_BOAT",
		INSIDE_BASKET: "INSIDE_BASKET",
		INSIDE_TUBE: "INSIDE_TUBE",
		INSIDE_COAL_MACHINE: "INSIDE_COAL_MACHINE",

		ON_ALTAR: "ON_ALTAR",
		ON_ATTIC_TABLE: "ON_ATTIC_TABLE",
		ON_KITCHEN_TABLE: "ON_KITCHEN_TABLE",
		ON_PEDESTAL: "ON_PEDESTAL",
		ON_RAILING: "ON_RAILING",

		PLAYER_INVENTORY: "PLAYER_INVENTORY",
		THIEF_INVENTORY: "THIEF_INVENTORY",
		TROLL_INVENTORY: "TROLL_INVENTORY",
		CYCLOPS_INVENTORY: "CYCLOPS_INVENTORY"
	},

	GAME_WORDS: [
		"a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
		"k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
		"u", "v", "w", "x", "y", "z", "ne", "nw", "se", "sw",
		"again", "all", "an", "and", "around", "at", "attach", "attack", "author",
		"bar", "bell", "bird", "bottle", "box", "bug", "but",
		"carpet", "case", "close",
		"door", "down", "drop",
		"east", "egg", "examine", "everything", "except", "exit",
		"five", "fuck",
		"giant", "go",
		"hand", "high", "highfive", "hit", "house",
		"in", "inn", "inside", "inventory", "it",
		"jump", "juniper",
		"key", "kick", "kitchen", "knife",
		"lantern", "leaflet", "light", "lock", "look",
		"mailbox", "move",
		"nest", "next", "north", "northeast", "northwest", "note",
		"odysseus", "off", "on", "open", "or", "out",
		"passage", "piano", "pick", "pile", "place", "put", "play", "please", "pull", "punch",
		"quit",
		"read", "ring", "room", "rope",
		"sack", "say", "scream", "shit", "shout", "slap", "songbird", "south", "southeast", "southwest", "store", "sword",
		"take", "the", "them", "tie", "to", "trap", "treasure", "treasures", "trophy", "turn",
		"ulysses", "unlock", "up",
		"wait", "walk", "west", "window", "with", "wizard",
		"yell"
	],

	THIEF_LOCATIONS: [
		"EAST_OF_CHASM", "GALLERY", "STUDIO", "EAST_WEST_PASSAGE", "ROUND_ROOM",
		"NARROW_PASSAGE", "MIRROR_ROOM_SOUTH", "WINDING_PASSAGE", "CAVE_SOUTH",
		"ALTAR", "TEMPLE", "EGYPTIAN_ROOM", "TORCH_ROOM", "DOME_ROOM",
		"ENGRAVINGS_CAVE", "DAMP_CAVE", "WHITE_CLIFFS_BEACH_NORTH", "WHITE_CLIFFS_BEACH_SOUTH",
		"DAM_BASE", "DAM", "DAM_LOBBY", "MAINTENANCE_ROOM", "NORTH_SOUTH_PASSAGE", "CHASM",
		"DEEP_CANYON", "RESERVOIR_SOUTH", "STREAM_VIEW", "RESERVOIR_EMPTY", "RESERVOIR_NORTH",
		"ATLANTIS_ROOM", "CAVE_NORTH", "TWISTING_PASSAGE", "MIRROR_ROOM_NORTH", "COLD_PASSAGE",
		"SLIDE_ROOM", "MINE_ENTRANCE", "SQUEAKY_ROOM", "SHAFT_ROOM", "SMELLY_ROOM", "GAS_ROOM",
		"COAL_MINE_1", "COAL_MINE_2", "COAL_MINE_3", "COAL_MINE_4", "LADDER_TOP",
		"LADDER_BOTTOM", "DEAD_END_COAL_MINE", "TIMBER_ROOM", "GRATING_ROOM", "TREASURE_ROOM",

		"MAZE_1", "MAZE_2", "MAZE_3", "MAZE_4", "MAZE_5", "MAZE_6", "MAZE_7", "MAZE_8",
		"MAZE_9", "MAZE_10", "MAZE_11", "MAZE_12", "MAZE_13", "MAZE_14", "MAZE_15",
		"DEAD_END_MAZE_NORTH","DEAD_END_MAZE_SOUTHEAST",
		"DEAD_END_MAZE_CENTER", "DEAD_END_MAZE_SOUTHWEST"
	],

	COAL_MINE: [
		"COAL_MINE_1", "COAL_MINE_2", "COAL_MINE_3", "COAL_MINE_4"
	],

	OVERWORLD: [
		"WEST_OF_HOUSE", "NORTH_OF_HOUSE", "BEHIND_HOUSE", "SOUTH_OF_HOUSE", "FOREST_PATH",
		"FOREST_WEST", "FOREST_EAST", "FOREST_NORTHEAST", "FOREST_SOUTH", "CLEARING_NORTH",
		"CLEARING_EAST", "CANYON_VIEW", "ROCKY_LEDGE", "CANYON_BOTTOM"
	],

	FOREST: [
		"FOREST_WEST", "FOREST_EAST", "FOREST_SOUTH", "FOREST_NORTHEAST"
	],
}